version: 2
jobs:
  test:
    docker:
    - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $GCLOUD_SERVICE_KEY
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn test -s /tools/m2/settings.xml
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  deploy-artifactory:
    docker:
    - image: eu.gcr.io/entur-system-1287/circleci-toolbox-image
      auth:
        username: _json_key
        password: $DOCKER_PASSWORD
    environment:
      MAVEN_OPTS: -Xmx3G
    steps:
    - checkout
    - restore_cache:
        key: dep-cache-{{ checksum "pom.xml" }}
    - run: mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.0:go-offline -s /tools/m2/settings.xml
    - save_cache:
        paths:
        - ~/.m2
        key: dep-cache-{{ checksum "pom.xml" }}
    # Cannot use -o because of snapshot dependencies.
    - run: mvn deploy -s /tools/m2/settings.xml -DskipTests
workflows:
  version: 2
  build_test_deploy:
    jobs:
    - test:
        context: org-carbon
    - deploy-artifactory:
        context: org-carbon
        requires:
        - test
        filters:
          branches:
            only: master